FORMAT: 1A

# Scan Invoice

Used to scan invoices and generate a JSON that can be used in other APIs.

# Group Interpretation

## Interpret [/interpret]

Interpret a scanned invoice.

### Start interpretation [POST]

+ Response 200 (application/json)

        { 
            "id": "1234" 
        }